CRE_BED: _artifacts/ENCFF234XEZ.bed.gz
fasta_path: _artifacts/GRCh38_no_alt_analysis_set_GCA_000001405.15.fasta.gz
dataloader:
  num_workers: 4
  batch_size: 8
  pin_memory: true
  drop_last: false
  prefetch_factor: 4
precision: bf16-mixed
